
[package]
authors = ["wukong<sec-wukong@outlook.com>"]
edition = "2021"
name = "galaxy_flow"
version = "0.2.5"


[[bin]]
name = "gm"
path = "src/app/gm/main.rs"

[[bin]]
name = "gx"
path = "src/app/gx/main.rs"

[workspace]
members = [
    ".",
    "crates/orion_common",
    "crates/orion_parse",
    "crates/orion_infra",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
winnow = "0.6"
orion-error = "0.1.13"


[dependencies]
orion_common = { path = "crates/orion_common" }
orion_parse = { path = "crates/orion_parse" }
orion_infra = { path = "crates/orion_infra" }
orion-exchange = "0.1"
derive-getters = "0.5"
derive_builder = "0.20"
duct = "0.13"

duct_sh = "0.13"
thiserror = "2.0"
handlebars = "6.3"
http-types = "2.12"
lazy_static = "1.4"
log = "0.4"
mockall = "0.13"
once_cell = "1.19"
pretty_env_logger = "0.5"
regex = "1.10"
rust-ini = "0.21"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shells = "0.2"
toml = "0.8"
url = "2.5"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.10.0"
os_info = "3"
winnow = "0.6"
colored = "3.0.0"
anyhow = "1.0.82"
include_dir = "0.7"
orion-error = { workspace = true }

[features]
res_depend_test = []


[dev-dependencies]
rstest = "0.25"
