# AI使用规则配置文件
# 定义每个角色如何正确使用AI的具体规则和指导原则

# 全局AI使用规则
global_ai_rules:
  # 基础原则
  principles:
    - "安全第一：始终确保AI使用不会泄露敏感信息"
    - "质量优先：追求高质量的输出结果"
    - "效率优化：合理使用AI资源，避免浪费"
    - "持续学习：根据使用反馈不断优化AI使用策略"
  
  # 通用约束
  constraints:
    max_tokens_per_request: 4000
    max_requests_per_minute: 10
    max_concurrent_requests: 3
    allowed_content_types: ["text", "code", "data"]
    forbidden_content: ["personal_info", "credentials", "proprietary_code"]
  
  # 质量标准
  quality_standards:
    min_response_quality: 0.7
    required_review: true
    validation_steps: ["accuracy_check", "relevance_check", "completeness_check"]
  
  # 安全要求
  security_requirements:
    data_encryption: true
    audit_logging: true
    access_control: true
    content_filtering: true

# 角色特定的AI使用规则
role_specific_rules:
  test_role:
    # 使用场景
    usage_scenarios:
      - "功能测试"
      - "集成测试"
      - "性能测试"
    
    # 特殊约束
    constraints:
      max_test_cases_per_session: 50
      allowed_test_types: ["unit", "integration", "e2e"]
      test_data_requirements: "匿名化测试数据"
    
    # 输出要求
    output_requirements:
      format: "structured_json"
      include_metrics: true
      error_handling: "detailed_error_reports"
    
    # 最佳实践
    best_practices:
      - "使用测试专用的AI模型"
      - "隔离测试环境"
      - "记录所有测试交互"
      - "定期验证测试结果"
  
  developer:
    # 使用场景
    usage_scenarios:
      - "代码生成"
      - "代码审查"
      - "架构设计"
      - "技术问题解决"
      - "文档生成"
    
    # 特殊约束
    constraints:
      max_code_length: 2000
      allowed_languages: ["rust", "python", "javascript", "go", "java"]
      code_review_required: true
      security_scan_required: true
    
    # 输出要求
    output_requirements:
      format: "well_formatted_code"
      include_comments: true
      include_tests: true
      error_handling: "graceful_error_handling"
    
    # 最佳实践
    best_practices:
      - "始终验证生成的代码"
      - "遵循项目编码规范"
      - "包含适当的错误处理"
      - "编写单元测试"
      - "避免生成敏感代码"
      - "使用版本控制管理生成的代码"
    
    # 禁止行为
    prohibited_actions:
      - "生成包含硬编码密钥的代码"
      - "生成不安全的代码模式"
      - "复制版权保护的代码"
      - "生成恶意代码"
  
  analyst:
    # 使用场景
    usage_scenarios:
      - "数据分析"
      - "趋势识别"
      - "报告生成"
      - "预测建模"
      - "可视化设计"
    
    # 特殊约束
    constraints:
      max_dataset_size: "100MB"
      allowed_data_formats: ["csv", "json", "parquet", "xlsx"]
      data_privacy_level: "high"
      statistical_validation_required: true
    
    # 输出要求
    output_requirements:
      format: "structured_analysis"
      include_visualizations: true
      include_confidence_intervals: true
      error_handling: "statistical_error_analysis"
    
    # 最佳实践
    best_practices:
      - "确保数据匿名化"
      - "验证数据质量"
      - "使用适当的统计方法"
      - "提供结果的不确定性评估"
      - "避免过度拟合"
      - "记录分析过程"
    
    # 禁止行为
    prohibited_actions:
      - "分析个人身份信息"
      - "做出未经证实的预测"
      - "忽略数据偏见"
      - "泄露敏感数据模式"
  
  writer:
    # 使用场景
    usage_scenarios:
      - "技术文档编写"
      - "创意写作"
      - "内容策划"
      - "编辑校对"
      - "翻译服务"
    
    # 特殊约束
    constraints:
      max_content_length: 5000
      allowed_content_types: ["technical", "creative", "marketing", "educational"]
      plagiarism_check_required: true
      style_consistency_required: true
    
    # 输出要求
    output_requirements:
      format: "well_structured_content"
      include_references: true
      grammar_check: true
      error_handling: "content_revision"
    
    # 最佳实践
    best_practices:
      - "保持内容原创性"
      - "适应目标受众"
      - "使用清晰简洁的语言"
      - "提供准确的引用"
      - "进行事实核查"
      - "维护品牌语调"
    
    # 禁止行为
    prohibited_actions:
      - "复制受版权保护的内容"
      - "生成误导性信息"
      - "创建有害内容"
      - "忽略文化敏感性"
  
  debugger:
    # 使用场景
    usage_scenarios:
      - "错误诊断"
      - "性能分析"
      - "日志分析"
      - "内存泄漏检测"
      - "并发问题排查"
    
    # 特殊约束
    constraints:
      max_log_size: "50MB"
      allowed_debug_levels: ["error", "warning", "info"]
      system_access_level: "read_only"
      production_safety_required: true
    
    # 输出要求
    output_requirements:
      format: "structured_debug_report"
      include_root_cause_analysis: true
      include_fix_suggestions: true
      error_handling: "diagnostics_with_solutions"
    
    # 最佳实践
    best_practices:
      - "在安全环境中进行调试"
      - "备份重要数据"
      - "记录调试步骤"
      - "验证修复方案"
      - "避免破坏性操作"
      - "使用适当的调试工具"
    
    # 禁止行为
    prohibited_actions:
      - "在生产环境直接修改代码"
      - "忽略系统安全限制"
      - "泄露系统敏感信息"
      - "执行未经验证的修复"
  
  reviewer:
    # 使用场景
    usage_scenarios:
      - "代码质量审查"
      - "安全审查"
      - "性能审查"
      - "架构审查"
      - "合规性检查"
    
    # 特殊约束
    constraints:
      max_review_files_per_session: 20
      allowed_review_types: ["code", "security", "performance", "architecture"]
      review_depth_level: "detailed"
      compliance_check_required: true
    
    # 输出要求
    output_requirements:
      format: "structured_review_report"
      include_severity_ratings: true
      include_action_items: true
      error_handling: "constructive_feedback"
    
    # 最佳实践
    best_practices:
      - "使用客观的审查标准"
      - "提供建设性的反馈"
      - "关注关键问题"
      - "考虑上下文因素"
      - "遵循审查清单"
      - "记录审查决策"
    
    # 禁止行为
    prohibited_actions:
      - "进行主观批评"
      - "忽略安全最佳实践"
      - "泄露代码细节"
      - "提出不切实际的要求"

# AI使用工作流程
ai_usage_workflows:
  # 通用工作流程
  common_workflow:
    steps:
      - name: "需求分析"
        description: "明确AI使用目标和要求"
        required: true
      - name: "规则检查"
        description: "验证使用请求符合AI使用规则"
        required: true
      - name: "权限验证"
        description: "确认用户具有相应权限"
        required: true
      - name: "内容准备"
        description: "准备和清理输入内容"
        required: true
      - name: "AI交互"
        description: "与AI进行交互"
        required: true
      - name: "结果验证"
        description: "验证AI输出的质量和准确性"
        required: true
      - name: "后处理"
        description: "对结果进行必要的后处理"
        required: false
      - name: "记录存档"
        description: "记录使用过程和结果"
        required: true
    
    # 质量控制点
    quality_checkpoints:
      - "输入内容合规性检查"
      - "AI输出质量评估"
      - "最终结果验证"
    
    # 异常处理
    exception_handling:
      - "规则违规处理"
      - "质量不达标处理"
      - "权限不足处理"
      - "系统错误处理"

# 监控和审计
monitoring_and_audit:
  # 使用指标
  usage_metrics:
    - "request_count"
    - "token_usage"
    - "response_time"
    - "error_rate"
    - "quality_score"
    - "user_satisfaction"
  
  # 审计日志
  audit_log:
    enabled: true
    retention_period: "90 days"
    log_level: "detailed"
    include_sensitive_data: false
  
  # 性能监控
  performance_monitoring:
    enabled: true
    alert_thresholds:
      response_time: "30s"
      error_rate: "5%"
      quality_score: "0.6"
    reporting_frequency: "daily"

# 培训和支持
training_and_support:
  # 用户培训
  user_training:
    required: true
    training_modules:
      - "AI使用基础"
      - "角色特定规则"
      - "安全最佳实践"
      - "质量标准"
    certification_required: true
    refresher_frequency: "quarterly"
  
  # 技术支持
  technical_support:
    available: true
    support_channels: ["email", "chat", "ticket"]
    response_time:
      critical: "1 hour"
      high: "4 hours"
      normal: "24 hours"
      low: "48 hours"
  
  # 文档资源
  documentation:
    user_guide: "/docs/ai_usage_guide.md"
    api_reference: "/docs/ai_api_reference.md"
    best_practices: "/docs/ai_best_practices.md"
    troubleshooting: "/docs/ai_troubleshooting.md"

# 元数据
metadata:
  version: "1.0.0"
  last_updated: "2025-06-17"
  description: "AI使用规则配置文件"
  author: "galaxy-flow"
  changelog:
    - "1.0.0": "初始版本，定义基本的AI使用规则和指导原则"
  review_cycle: "quarterly"
  next_review_date: "2025-09-17"