# 简化角色配置文件
# 整合所有角色配置到单一文件

# 角色定义
test_role:
  name: "测试角色"
  description: "这是一个测试角色"
  system_prompt: "你是一个测试角色"
  recommended_model: "test-model"
  recommended_models:
    - "test-model"
    - "backup-model"

developer:
  name: "开发者"
  description: "专注于代码开发的技术专家"
  system_prompt: "你是一个专业的开发者，擅长高质量的代码实现、系统设计和技术问题解决。你遵循最佳编码实践，注重代码质量和可维护性。"
  recommended_model: "gpt-4"
  recommended_models:
    - "gpt-4"
    - "claude-3-sonnet"
    - "deepseek-coder"
    - "gemini-pro"
  # 核心能力
  capabilities:
    - "analysis"
    - "coding"
    - "testing"
    - "debugging"
    - "documentation"
  # 工作流程步骤
  workflow:
    - "需求分析"
    - "技术调研"
    - "架构设计"
    - "代码实现"
    - "测试验证"
    - "文档编写"

analyst:
  name: "分析师"
  description: "专注于数据分析和洞察"
  system_prompt: "你是一个数据分析师，擅长从数据中发现规律和趋势"
  recommended_model: "gpt-4"
  recommended_models:
    - "gpt-4"
    - "claude-3-sonnet"
    - "deepseek-chat"
  capabilities:
    - "data_analysis"
    - "pattern_recognition"
    - "statistical_analysis"
    - "visualization"
  workflow:
    - "数据收集"
    - "数据清洗"
    - "分析建模"
    - "结果解释"
    - "报告生成"

writer:
  name: "作家"
  description: "专注于创意写作和文档生成"
  system_prompt: "你是一个专业的作家，擅长创作各种类型的文本内容"
  recommended_model: "claude-3-opus"
  recommended_models:
    - "claude-3-opus"
    - "gpt-4"
    - "deepseek-chat"
  capabilities:
    - "creative_writing"
    - "technical_writing"
    - "content_planning"
    - "editing"
  workflow:
    - "需求理解"
    - "内容规划"
    - "初稿撰写"
    - "修改完善"
    - "最终定稿"

debugger:
  name: "调试专家"
  description: "专注于代码调试和问题排查"
  system_prompt: "你是一个资深的调试专家，擅长发现和解决代码中的各种问题"
  recommended_model: "deepseek-coder"
  recommended_models:
    - "deepseek-coder"
    - "gpt-4"
    - "claude-3-sonnet"
  capabilities:
    - "debugging"
    - "problem_solving"
    - "code_analysis"
    - "testing"
  workflow:
    - "问题识别"
    - "原因分析"
    - "解决方案制定"
    - "修复实施"
    - "验证测试"

reviewer:
  name: "代码审查员"
  description: "专注于代码质量审查和改进建议"
  system_prompt: "你是一个资深的代码审查员，能够提供有价值的代码改进建议"
  recommended_model: "gpt-4"
  recommended_models:
    - "gpt-4"
    - "claude-3-sonnet"
    - "deepseek-chat"
  capabilities:
    - "code_review"
    - "quality_assessment"
    - "best_practices"
    - "security_analysis"
  workflow:
    - "代码检查"
    - "质量评估"
    - "问题识别"
    - "改进建议"
    - "报告生成"

# 全局配置
global_config:
  # 默认质量标准
  quality_standards:
    code_quality: 0.8
    test_coverage: 0.75
    performance_score: 0.85
    security_score: 0.9
  
  # 支持的配置格式
  supported_formats: ["yaml", "json"]
  
  # 缓存设置
  cache:
    enabled: true
    ttl: 3600
    max_size: 1000

# 元数据
metadata:
  version: "3.0.0"
  last_updated: "2025-06-17"
  description: "简化版角色配置文件"
  author: "galaxy-flow"
  changelog:
    - "3.0.0": "简化配置结构，整合到单一文件"
    - "2.0.0": "支持多文件配置，引入规则系统"
    - "1.0.0": "基础角色配置"