[package]
name = "orion_cond"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
getset = "0.1.6"
chrono = "0.4.41"

wildmatch = "~2.4"
derive_more = { workspace = true }
contracts = "0.6"
libc = "0.2.174"
ipnet = "~2.11"


[dev-dependencies]
rstest = "0.26"
tempfile = "3.10"
