name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Code formatting check
      run: cargo fmt -- --check
    - name: Code linting
      run: cargo clippy -- -D warnings --allow clippy::result-large-err
    - name: Build Artifacts
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Debug build output
      run: ls -l target/x86_64-unknown-linux-gnu/release/

    - name: Upload Artifacts
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: target/x86_64-unknown-linux-gnu/release/
        retention-days: 5
