name: Rust

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Code formatting check
      run: cargo fmt -- --check
    - name: Code linting
      run: cargo clippy -- -D warnings
    - name: Build Artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        mkdir -p artifacts
        cp target/x86_64-unknown-linux-gnu/release/gm artifacts/
        cp target/x86_64-unknown-linux-gnu/release/gx artifacts/
