name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        profile: minimal

    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
    - name: Code formatting check
      run: cargo fmt -- --check
    - name: Code linting
      run: cargo clippy -- -D warnings --allow clippy::result-large-err
    - name: Build Artifacts
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target ${{ matrix.target }}

    - name: Debug build output
      run: ls -l target/${{ matrix.target }}/release/

    - name: Upload Artifacts
      if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: galaxy_flow-${{ matrix.os }}
        path: |
          target/${{ matrix.target }}/release/gm
          target/${{ matrix.target }}/release/gx
        retention-days: 5
